[project]
name = "mimic-preprocessor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipdb>=0.13.13",
    "matplotlib>=3.10.8",
    "pandas>=2.3.1",
    "pyarrow>=20.0.0",
    "tomli>=2.2.1",
    "tqdm>=4.67.1",
]
