basic_features = ["PatientID", "RecordTime"]
label_features = ["Outcome", "LOS", "Readmission"]
demographic_features = ["Age", "Sex"]
gcs_features = [
    "Glascow coma scale eye opening",
    "Glascow coma scale motor response",
    "Glascow coma scale verbal response"
]
labtest_features = [
    "Capillary refill rate",
    "Diastolic blood pressure",
    "Fraction inspired oxygen",
    "Glascow coma scale eye opening",
    "Glascow coma scale motor response",
    "Glascow coma scale total",
    "Glascow coma scale verbal response",
    "Glucose",
    "Heart Rate",
    "Height",
    "Mean blood pressure",
    "Oxygen saturation",
    "Respiratory rate",
    "Systolic blood pressure",
    "Temperature",
    "Weight",
    "pH"
]

[one_hot_labtest_features]
"Capillary refill rate->0.0" = true
"Capillary refill rate->1.0" = true
"Glascow coma scale eye opening->1 No response" = true
"Glascow coma scale eye opening->2 To pain" = true
"Glascow coma scale eye opening->3 To speech" = true
"Glascow coma scale eye opening->4 Spontaneously" = true
"Glascow coma scale motor response->1 No response" = true
"Glascow coma scale motor response->2 Abnormal extension" = true
"Glascow coma scale motor response->3 Abnormal flexion" = true
"Glascow coma scale motor response->4 Flex-withdraws" = true
"Glascow coma scale motor response->5 Localizes pain" = true
"Glascow coma scale motor response->6 Obeys commands" = true
"Glascow coma scale total->3" = true
"Glascow coma scale total->4" = true
"Glascow coma scale total->5" = true
"Glascow coma scale total->6" = true
"Glascow coma scale total->7" = true
"Glascow coma scale total->8" = true
"Glascow coma scale total->9" = true
"Glascow coma scale total->10" = true
"Glascow coma scale total->11" = true
"Glascow coma scale total->12" = true
"Glascow coma scale total->13" = true
"Glascow coma scale total->14" = true
"Glascow coma scale total->15" = true
"Glascow coma scale verbal response->1 No response-ETT" = true
"Glascow coma scale verbal response->2 Incomprehensible sounds" = true
"Glascow coma scale verbal response->3 Inappropriate words" = true
"Glascow coma scale verbal response->4 Confused" = true
"Glascow coma scale verbal response->5 Oriented" = true

[is_categorical_channel]
"Capillary refill rate" = true
"Diastolic blood pressure" = false
"Fraction inspired oxygen" = false
"Glascow coma scale eye opening" = true
"Glascow coma scale motor response" = true
"Glascow coma scale total" = true
"Glascow coma scale verbal response" = true
"Glucose" = false
"Heart Rate" = false
"Height" = false
"Mean blood pressure" = false
"Oxygen saturation" = false
"Respiratory rate" = false
"Systolic blood pressure" = false
"Temperature" = false
"Weight" = false
"pH" = false

[possible_values]
"Capillary refill rate" = [
    [0, "0"],
    [1, "1"],
]
"Diastolic blood pressure" = []
"Fraction inspired oxygen" = []
"Glascow coma scale eye opening" = [
    [1, "No response"],
    [2, "To pain"],
    [3, "To speech"],
    [4, "Spontaneously"],
]
"Glascow coma scale motor response" = [
    [1, "No response"],
    [2, "Abnormal extension"],
    [3, "Abnormal flexion"],
    [4, "Flex-withdraws"],
    [5, "Localizes pain"],
    [6, "Obeys commands"],
]
"Glascow coma scale total" = [
    [3, "3"],
    [4, "4"],
    [5, "5"],
    [6, "6"],
    [7, "7"],
    [8, "8"],
    [9, "9"],
    [10, "10"],
    [11, "11"],
    [12, "12"],
    [13, "13"],
    [14, "14"],
    [15, "15"],
]
"Glascow coma scale verbal response" = [
    [1, "No response-ETT"],
    [2, "Incomprehensible sounds"],
    [3, "Inappropriate words"],
    [4, "Confused"],
    [5, "Oriented"],
]
"Glucose" = []
"Heart Rate" = []
"Height" = []
"Mean blood pressure" = []
"Oxygen saturation" = []
"Respiratory rate" = []
"Systolic blood pressure" = []
"Temperature" = []
"Weight" = []
"pH" = []

[normal_values]
"Capillary refill rate" = "0.0"
"Diastolic blood pressure" = "59.0"
"Fraction inspired oxygen" = "0.21"
"Glascow coma scale eye opening" = "4 Spontaneously"
"Glascow coma scale motor response" = "6 Obeys Commands"
"Glascow coma scale total" = "15"
"Glascow coma scale verbal response" = "5 Oriented"
"Glucose" = "128.0"
"Heart Rate" = "86"
"Height" = "170.0"
"Mean blood pressure" = "77.0"
"Oxygen saturation" = "98.0"
"Respiratory rate" = "19"
"Systolic blood pressure" = "118.0"
"Temperature" = "36.6"
"Weight" = "81.0"
"pH" = "7.4"